rename UserAuth to WebAuth
yiisoft/user pull request #105
Opened 2024-10-23 14:39 UTC by olegbaturin

rename UserAuth to WebAuth
add ApiAuth

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ✔️/❌

#101

2024-10-24 08:20 UTC, vjik requested changes

2024-10-24 08:20 UTC, vjik commented on config/di-web.php
> +    WebAuth::class => [
For BC need keep `UserAuth` definition also

2024-10-24 08:20 UTC, vjik commented on CHANGELOG.md
> +- Enh #101: Add `ApiAuth` authentication method (@olegbaturin)
```suggestion
- New #101: Add `ApiAuth` authentication method (@olegbaturin)
```

2024-10-24 08:58 UTC, vjik approved these changes

2024-10-24 08:58 UTC, vjik commented on tests/WebAuthTest.php
Keep `UserAuthTest` also.

2024-10-26 20:53 UTC, samdark requested changes

2024-10-26 20:53 UTC, samdark commented on README.md
> +In order to use `Yiisoft\User\Method\ApiAuth` as an authentication method, you need to define it as an implementation of `Yiisoft\Auth\AuthenticationMethodInterface` in the DI container configuration
```suggestion
To use `Yiisoft\User\Method\ApiAuth` as an authentication method, you need to define it as an implementation of `Yiisoft\Auth\AuthenticationMethodInterface` in the DI container configuration
```

2024-10-26 20:53 UTC, samdark commented on src/Method/ApiAuth.php
> +    public function __construct(private CurrentUser $currentUser)
```suggestion
    public function __construct(private readonly CurrentUser $currentUser)
```

2024-10-26 20:53 UTC, samdark commented on src/Method/WebAuth.php
> +    public function __construct(private CurrentUser $currentUser, private ResponseFactoryInterface $responseFactory)
```suggestion
    public function __construct(
    	private readonly CurrentUser $currentUser,
    	private readonly ResponseFactoryInterface $responseFactory
	)
```

2024-10-26 20:53 UTC, samdark commented on src/UserAuth.php
> + * @deprecated Use {@see \Yiisoft\User\Method\WebAuth}. Will remove in the next major version.
```suggestion
 * @deprecated Use {@see \Yiisoft\User\Method\WebAuth}. We will remove this class in the next major version.
```

2024-10-26 20:53 UTC, samdark commented on tests/ApiAuthTest.php
> +        $result = (new ApiAuth($user, new ResponseFactory()))->authenticate(new ServerRequest());
```suggestion
        $result = (new ApiAuth($user))->authenticate(new ServerRequest());
```

There's only one argument accepted, not two.

2024-10-26 20:53 UTC, samdark commented on tests/ApiAuthTest.php
> +        $result = (new ApiAuth($user, new ResponseFactory()))->authenticate(new ServerRequest());
```suggestion
        $result = (new ApiAuth($user))->authenticate(new ServerRequest());
```

2024-10-26 20:53 UTC, samdark commented on tests/ApiAuthTest.php
> +        $challenge = (new ApiAuth($user, new ResponseFactory()))->challenge($response);
```suggestion
        $challenge = (new ApiAuth($user))->challenge($response);
```

2024-10-28 14:00 UTC, samdark approved these changes

2024-11-11 08:04 UTC, samdark approved these changes

2024-11-11 08:06 UTC, merged

2024-11-11 08:06 UTC, samdark commented
Thank you!